security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/backend
            provider: usuarios
            form_login:
                login_path: backend_login
                check_path: backend_login_check
                default_target_path: backend_homepage
                remember_me: true
                use_referer: true
            logout:
                path: backend_logout
                target: backend_login
            security: true
            anonymous: true
        frontend:
            pattern:  ^/pakmail
            provider: clientes
            form_login:
                login_path: pakmail_login
                check_path: pakmail_login_check
                default_target_path: pakmail_envios
                remember_me: true
                use_referer: true
            logout:
                path: pakmail_logout
                target: pakmail_login
            remember_me:
                key:        pakmail1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
            security: true
            anonymous: true

    access_control:
        - { path: ^/pakmail/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pakmail/recuperar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pakmail, roles: [ROLE_CLIENTE] }
        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/recuperar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend, roles: [ROLE_ADMIN] }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    encoders:
        InteractiveValley\BackendBundle\Entity\Usuario:  { algorithm: sha512, iterations: 10 }
        InteractiveValley\PakmailBundle\Entity\Cliente:  plaintext
        Symfony\Component\Security\Core\User\User: sha512


    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: InteractiveValley\BackendBundle\Entity\Usuario, property: email }
        clientes:
            entity: { class: InteractiveValley\PakmailBundle\Entity\Cliente, property: email }
        administradores:
            memory:
                users:
                    admin: { password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: [ ROLE_ADMIN ] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_CLIENTE
        ROLE_API:         ROLE_CLIENTE
        ROLE_SUPER_ADMIN: [ROLE_CLIENTE, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]