security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/backend
            provider: usuarios
            form_login:
                login_path: backend_login
                check_path: backend_login_check
                remember_me: true
                use_referer: true
            logout:
                path: backend_logout
                target: backend_login
            security: true
            anonymous: true
        frontend:
            pattern:  ^/pakmail
            provider: usuarios
            form_login:
                login_path: pakmail_login
                check_path: pakmail_login_check
                remember_me: true
                use_referer: true
            logout:
                path: pakmail_logout
                target: homepage
            remember_me:
                key:        pakmail1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
            security: true
            anonymous: true

    access_control:
        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend, roles: [ROLE_ADMIN] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pakmail/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pakmail, roles: [ROLE_USER] }

    encoders:
        InteractiveValley\BackendBundle\Entity\Usuario:  { algorithm: sha512, iterations: 10 }


    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: InteractiveValley\BackendBundle\Entity\Usuario, property: email }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]