# app/config/services.yml
services:
    richpolis.security.authentication_handler:
        class: InteractiveValley\FrontendBundle\Handler\AuthenticationHandler
        public: false
        arguments:
            - @router
            - @session

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

#    login_listener:
#        class: InteractiveValley\FrontendBundle\Listener\LoginListener
#        arguments: [@service_container,@security.context, @router]
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login }
#            - { name: kernel.event_listener, event: kernel.response }
