<?php

namespace InteractiveValley\PakmailBundle\Repository;

/**
 * DireccionRemisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionRemisionRepository extends \Doctrine\ORM\EntityRepository
{
}
