<?php

namespace InteractiveValley\PakmailBundle\Repository;

/**
 * DireccionFiscalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionFiscalRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPaises()
    {
        $em=$this->getEntityManager();
       
        $query=$em->createQuery('
            SELECT DISTINCT e.pais as value    
            FROM PakmailBundle:DireccionFiscal e
        ');
        
        $paises=$query->getResult();
        return $paises;
    }
	
	public function getArrayPaises(){
		$paises = $this->getPaises();
		$arreglo = array();
		foreach($paises as $pais){
			$arreglo[]=$pais['value'];
		}
		$convinado = array_combine($arreglo,$arreglo);
		return $convinado;
	}
}
