<?php

namespace InteractiveValley\PakmailBundle\Repository;

/**
 * DireccionDestinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionDestinoRepository extends \Doctrine\ORM\EntityRepository
{
}
