<?php

namespace InteractiveValley\PakmailBundle\Repository;

/**
 * DireccionFiscalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionFiscalRepository extends \Doctrine\ORM\EntityRepository
{
}
