<?php

namespace InteractiveValley\PakmailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends EntityRepository
{   
    public function queryFindByActive()
    {
        $query= $this->getEntityManager()->createQueryBuilder();
        $query->select('e')
                ->from('InteractiveValley\PakmailBundle\Entity\Evento', 'e')
                ->where('c.isActive=:activo')
                ->setParameter('activo', true)
                ->orderBy('e.position', 'ASC');
        return $query->getQuery();
    }
    
    public function findByActive()
    {
        $query= $this->queryFindByActive();
        return $query->getResult();
    }
}
