<?php

namespace InteractiveValley\PakmailBundle\Repository;

/**
 * FechaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FechaRepository extends \Doctrine\ORM\EntityRepository
{
}
