<?php

namespace InteractiveValley\PakmailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntaRepository extends EntityRepository
{
    public function getMaxPosicion()
    {
        $em=$this->getEntityManager();
       
        $query=$em->createQuery('
            SELECT MAX(e.position) as value 
            FROM PakmailBundle:Pregunta e 
            ORDER BY e.position ASC
        ');
        
        $max=$query->getResult();
        return $max[0]['value'];
    }
}
