<?php

namespace InteractiveValley\PakmailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends EntityRepository
{
    public function getMaxPosicion()
    {
        $em=$this->getEntityManager();
       
        $query=$em->createQuery('
            SELECT MAX(e.position) as value 
            FROM PakmailBundle:Servicio e 
            ORDER BY e.position ASC
        ');
        
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
    public function queryFindByActive()
    {
        $query= $this->getEntityManager()->createQueryBuilder();
        $query->select('e')
                ->from('InteractiveValley\PakmailBundle\Entity\Servicio', 'e')
                ->where('c.isActive=:activo')
                ->setParameter('activo', true)
                ->orderBy('e.position', 'ASC');
        return $query->getQuery();
    }
    
    public function findByActive()
    {
        $query= $this->queryFindByActive();
        return $query->getResult();
    }
}
